### ISSUE TITLE
Final problems that should be addressed before handing in milestone 3

### ISSUE THREAD

**Issue by danfke** [UBC-MDS/Collision_Prediction#54]

**Comment by danfke** [comment]
- [x] As mentioned by @gfairbro there is a problem with rendering png from altair on certain windows machines. Not really sure how to implement this if it doesnt work by putting it in the environment file. I'm mostly worried that if a TA happens to have a computer where it won't render then we will lose marks because they can't reproduce our project.

"The environment is missing something for the EDA in windows. I know this because our project is too! in order to output PNG in windows from altair you need to run the following, and it doesnt seem to get captured properly when you export a environment.yaml file:
npm install -g vega vega-cli vega-lite canvas
(see lecture 2 from 531 for details - scroll down to the warning):
https://pages.github.ubc.ca/mds-2021-22/DSCI_531_viz-1_students/lectures/2-data-types_graphical-marks_visual-encondings.html#global-development-data
"

Add to dependencies:

For Windows users, run this command prior to running eda.py:

`npm install -g vega vega-cli vega-lite canvas`

**Comment by danfke** [comment]
- [ ] Our figure captions don't render properly in .md. Tiffany suggested that we either use pdf for our report, or html and create a GitHub pages. If anyone know how to do the latter it would be nice. When I looked into it, it was more complicated than I was expecting.

**Comment by danfke** [comment]
Should we actually get rid of some of ther version specified in the environment because it may hinder cross-platform compatibility?

**Comment by danfke** [comment]
There is now a figure folder containing our figure, but the figures are also saved outside of the folder

**Comment by danfke** [comment]
- [x] Since the report references the figures outside of the folder, I think we should just delete the figures folder

**Comment by danfke** [comment]
- [ ] Add tests for each script
- [ ] Add documentation for defined functions

**Comment by gfairbro** [comment]
I would suggest just adding a blurb in your usage asking windows users to run the install command I quoted. You can check ours if you like. Group 19.

**Comment by danfke** [comment]
> I would suggest just adding a blurb in your usage asking windows users to run the install command I quoted. You can check ours if you like. Group 19.

Thanks @gfairbro we are adding it to our next PR :)
