### ISSUE TITLE
Address feedback from Milestone 2

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/Collision_Prediction#58]
**TA feedback** - All that need to be addressed are related to "Writing analysis that uses multiple scripts" section:

- [x] Link to report in the README is broken
- [x] Is the md file in the doc section an incomplete version of the report?
- [x] Include more detailed discussion of results and conclusions
- [x] What features were removed in feature selection? Did this change the score?
- [x] Define the variables, which ones are relevant to the model and does it make sense?
- [x] Got C for visualization? What improvements are needed?
- [x] Format dates (shouldn't include commas)
- [x] Categorical features should not be presented as numerical features (e.g. P_SEX does not need a decimal place)
- [x] Include authors and abstract in the report
- [x] Check writing "the model predicts false positives" - not sure what you mean by "the data set has false positives"?

**Peer feedback** - https://github.com/UBC-MDS/data-analysis-review-2021/issues/29

**Comment by iamMoid** [comment]
All issues addressed.
